name: Trigger GitHub Index Update (branch test)

on:
  push:
    branches:
      - main

jobs:
  trigger-index-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Index Update Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_INDEX_REPO_TRIGGER_PAT }}
        run: |
          gh workflow run watchlist-repo-1-updated.yml --repo ${{ secrets.GH_INDEX_REPO_URL }}